### ISSUE TITLE
GitHub Actions script failing in private repo due to missing "contents: read" permission

### ISSUE THREAD

**Issue by scorpion9979** [ScopeLift/foundry-template#17]
**Description**
I encountered an issue with the GitHub Actions script when the repo created via the template is private. It seems that the script is unable to access the repository's contents due to missing permissions.

**To Reproduce**
To reproduce the behavior, you need to create a private repository on GitHub via the template. Notice that the workflow fails due to a lack of permissions to access the repository's content.

**Proposed Solution**
To fix this issue, kindly add the "contents: read" permission to the workflow file in the permissions section. Here's an example:

```yaml
  slither-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
...
```
